# site settings

title: Diogo Freire
description: Website for Diogo Freire, from Papamoa NZ
taglong: Product/Project Manager and Weightlifter
tagshort: Product/Project Manager and Weightlifter
url: https://diogofreire.com
baseurl: ""
permalink: pretty

# author settings

author:
  name: 
  email: me@diogofreire.com
photo: /assets/jpg/diogo_freire.jpeg

# social media links

social:
  #facebook: username
  #github: username
  instagram: diogo.lifts.things
  linkedin: diogofreire
  #stackoverflow: 0000000/username
  #twitter: username

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
